# Generated by Django 4.1.5 on 2023-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Ник')),
                ('hometown', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('age_from', models.CharField(max_length=100, verbose_name='Возрас от')),
                ('age_to', models.CharField(max_length=100, verbose_name='возраст до')),
            ],
        ),
    ]
